services:
  ezdeliver-php:
    user: $UID
    build: './php'
    volumes:
      - ../:/app
      - ../var:/root/.ez
      - ../var/testsrc:/test
      - ../var/test2:/test2
      - ../../.ssh:/root/.ssh
      - ./php/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
